### ISSUE TITLE
Columns not sortable with large dataset

### ISSUE THREAD

**Issue by decay29** [ackerleytng/logaze#29]
If there are more than a few hundred items in the list, the column sort does not work unless it is filtered down.  Earlier today, they were refreshing, and there were 200 laptops, and clicking a column worked fine.  Now there are over 600, and I have to filter on something (like RAM) in order to get the list sorted by a column.

Thanks for this tool.  I have already purchased two laptops, and it is so much better than suffering through the Lenovo outlet.

**Comment by ackerleytng** [comment]
Thanks for your continued usage! I'm happy that this was useful to you.

I think it should be fixed now, the issue was probably some null values in the data, which @shurane noticed and fixed in #30.

If you're still facing issues, #30 also upgraded ag-grid, so the old column sorting/filtering state may no longer be usable with the new version of ag-grid. 

Please try clearing localStorage for logaze. Here are some instructions for chrome: https://developer.chrome.com/docs/devtools/storage/localstorage/

I'm working on a reset button to make clearing old setting easier. 

Meanwhile, if the above works for you, please close this issue, thanks! I'll close this issue in a few days if there are no further updates. :)

**Comment by decay29** [comment]
Works like a champ.  Thanks.
